---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nonsense
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infra/kubernetes/cluster-01/nonsense
  prune: true
  sourceRef:
    kind: GitRepository
    name: code
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
