apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  namespace: flux-system
  name: tailscale
spec:
  interval: 10m0s
  path: ./infra/kubernetes/cluster-02/tailscale
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
