load("@aspect_rules_js//js:defs.bzl", "js_library")

js_library(
    name = "public",
    srcs = [
        "image.jpg",
        "image (1).jpg",
        "next.svg",
        "vercel.svg",
    ],
    visibility = ["//projects/wedding:__subpackages__"],
)
