oci = use_extension("@rules_oci//oci:extensions.bzl", "oci")

# renovate: datasource=docker depName=docker.io/linuxserver/prowlarr
oci.pull(
    name = "prowlarr",
    digest = "sha256:c7502a75b021d964481c129c84590b9cbc40f83aadd4e553f173871bc0deaa3c",
    image = "docker.io/linuxserver/prowlarr",
    platforms = [
        "linux/amd64",
        "linux/arm64",
    ],
)
use_repo(
    oci,
    "prowlarr",
    "prowlarr_linux_amd64",
    "prowlarr_linux_arm64",
)
