---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  namespace: arrs
  labels:
    app: jackett
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jackett
  template:
    metadata:
      labels:
        app: jackett
    spec:
      serviceAccountName: "tailscale"
      containers:
        - name: jackett
          image: lscr.io/linuxserver/jackett:latest
          env:
            - name: TZ
              value: Europe/London
            - name: PUID
              value: "1001"
            - name: PGID
              value: "1001"
          ports:
            - name: web
              containerPort: 9117
          volumeMounts:
            - mountPath: /config
              name: jackett-config-storage
            - mountPath: /downloads
              name: downloads
        - name: ts-sidecar
          imagePullPolicy: Always
          image: "ghcr.io/tailscale/tailscale:latest"
          env:
            # Store the state in a k8s secret
          - name: TS_KUBE_SECRET
            value: "tailscale-auth"
          - name: TS_USERSPACE
            value: "false"
          - name: TS_DEBUG_FIREWALL_MODE
            value: auto
          - name: TS_EXTRA_ARGS
            value: "--accept-routes --accept-dns=true --exit-node-allow-lan-access --exit-node=100.111.198.95"
          - name: TS_AUTHKEY
            valueFrom:
              secretKeyRef:
                name: tailscale-auth
                key: TS_AUTHKEY
                optional: true
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_UID
            valueFrom:
              fieldRef:
                fieldPath: metadata.uid
          securityContext:
            privileged: true

      volumes:
        - name: jackett-config-storage
          hostPath:
            path: /mnt/pool_01/media-server-config/jackett
        - name: downloads
          hostPath:
            path: /mnt/pool_01/Downloads
---
apiVersion: v1
kind: Service
metadata:
  name: jackett
  namespace: arrs
spec:
  type: NodePort
  selector:
    app: jackett
  ports:
    - protocol: TCP
      port: 9117
      nodePort: 19117
