---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: arrs
  labels:
    app: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      serviceAccountName: "tailscale"
      containers:
        - name: prowlarr
          image: ghcr.io/amriksd/prowlarr@sha256:92171e337c9fb70dd9b2dc6f0a61df4fef0f5f349cc7c1562bf457f36bd1b6fe
          env:
            - name: TZ
              value: Europe/London
            - name: PUID
              value: "1001"
            - name: PGID
              value: "1001"
          ports:
            - name: web
              containerPort: 9696
          volumeMounts:
            - mountPath: /config
              name: prowlarr-config-storage
        - name: ts-sidecar
          imagePullPolicy: Always
          image: "ghcr.io/tailscale/tailscale:latest"
          env:
            # Store the state in a k8s secret
          - name: TS_KUBE_SECRET
            value: "tailscale-auth"
          - name: TS_USERSPACE
            value: "false"
          - name: TS_DEBUG_FIREWALL_MODE
            value: auto
          - name: TS_EXTRA_ARGS
            value: "--reset"
          - name: TS_AUTHKEY
            valueFrom:
              secretKeyRef:
                name: tailscale-auth
                key: TS_AUTHKEY
                optional: true
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_UID
            valueFrom:
              fieldRef:
                fieldPath: metadata.uid
          securityContext:
            privileged: true

      volumes:
        - name: prowlarr-config-storage
          hostPath:
            path: /mnt/pool_01/media-server-config/prowlarr
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: arrs
spec:
  type: NodePort
  selector:
    app: prowlarr
  ports:
    - protocol: TCP
      port: 9696
      nodePort: 19696
