---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: arrs
  labels:
    app: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
        - name: qbittorrent
          image: ghcr.io/amriksd/qbittorrent@sha256:dbd95f9f81be435543b72bc02e1195139fab2ed4657f26460a2df489ca608825
          env:
            - name: TZ
              value: Europe/London
            - name: PUID
              value: "1001"
            - name: PGID
              value: "1001"
          ports:
            - name: web
              containerPort: 7878
          volumeMounts:
            - mountPath: /config
              name: qbittorrent-config-storage
            - mountPath: /movies
              name: movies-nfs
            - mountPath: /downloads
              name: downloads-nfs
      volumes:
        - name: qbittorrent-config-storage
          hostPath:
            path: /mnt/pool_01/media-server-config/qbittorrent
        - name: downloads-nfs
          hostPath:
            path: /mnt/pool_01/Downloads
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: arrs
spec:
  type: NodePort
  selector:
    app: qbittorrent
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 18080
    - protocol: TCP
      port: 6881
      nodePort: 6881
    - protocol: UDP
      port: 6881
      nodePort: 6881
