---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: arrs
  labels:
    app: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
        - name: qbittorrent
          image: ghcr.io/amriksd/qbittorrent@sha256:f0a923216f4353f29a489c516a6e15572e48ccee2174625e2181da10e19f1745
          env:
            - name: TZ
              value: Europe/London
            - name: PUID
              value: "1001"
            - name: PGID
              value: "1001"
            - name: WEBUI_PORT
              value: "8080"
            - name: TORRENTING_PORT
              value: "6881"
          ports:
            - name: web
              containerPort: 8080
            - name: torrent
              containerPort: 6881
          volumeMounts:
            - mountPath: /config
              name: qbittorrent-config-storage
            - mountPath: /downloads
              name: downloads-nfs
      volumes:
        - name: qbittorrent-config-storage
          hostPath:
            path: /mnt/pool_01/media-server-config/qbittorrent
        - name: downloads-nfs
          hostPath:
            path: /mnt/pool_01/Downloads
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: arrs
spec:
  type: NodePort
  selector:
    app: qbittorrent
  ports:
    - protocol: TCP
      name: web
      port: 8080
      nodePort: 18080
    - protocol: TCP
      name: torrent
      port: 6881
      nodePort: 6881
    - protocol: UDP
      name: torrent-udp
      port: 6881
      nodePort: 6881
