---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: arrs
  labels:
    app: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
        - name: sonarr
          image: ghcr.io/amriksd/sonarr@sha256:075fdc242d8b54a6f5c890b31bac2a9e287c318a820ea746f40869a0820a0ffc
          env:
            - name: TZ
              value: Europe/London
            - name: PUID
              value: "1001"
            - name: PGID
              value: "1001"
          ports:
            - name: web
              containerPort: 8989
          volumeMounts:
            - mountPath: /config
              name: sonarr-config-storage
            - mountPath: /movies
              name: movies-nfs
            - mountPath: /downloads
              name: downloads-nfs
      volumes:
        - name: sonarr-config-storage
          hostPath:
            path: /mnt/pool_01/media-server-config/sonarr
            type: ""
        - name: movies-nfs
          hostPath:
            path: /mnt/pool_01/Plex
            type: ""
        - name: downloads-nfs
          hostPath:
            path: /mnt/pool_01/ix-applications/releases/qbittorrent/volumes/ix_volumes/config/Downloads
            type: ""
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: arrs
spec:
  type: NodePort
  selector:
    app: sonarr
  ports:
    - protocol: TCP
      port: 8989
      nodePort: 18989
