apiVersion: apps/v1
kind: Deployment
metadata:
  name: unpoller
  namespace: monitoring
  labels:
    app: unpoller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unpoller
  template:
    metadata:
      labels:
        app: unpoller
    spec:
      containers:
        - name: unpoller
          image: ghcr.io/unpoller/unpoller:v2.11.2
          env:
            - name: UP_INFLUXDB_DISABLE
              value: true
            - name: UP_UNIFI_DEFAULT_PASS
              value: "${SECRET_UNPOLLER_PASSWORD}" 
            - name: UP_UNIFI_CONTROLLER_0_URL
              value: 10.0.0.1
          ports:
            - name: metrics
              containerPort: 9130
