---
apiVersion: v1
kind: Service
metadata:
  name: unpoller
  namespace: monitoring
  labels:
    app: unpoller
spec:
  selector:
    app: unpoller
  ports:
    - name: metrics 
      protocol: TCP
      port: 9130
      targetPort: metrics
