---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: minio
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: operator
      version: 5.0.15
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: default
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
