load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "onboard_lib",
    srcs = ["main.go"],
    importpath = "github.com/amriksd/code/projects/onboard/cmd/onboard",
    visibility = ["//visibility:private"],
    deps = [
        "//projects/onboard/internal/github",
        "//projects/onboard/internal/tui",
        "//projects/onboard/internal/workspace",
    ],
)

go_binary(
    name = "onboard",
    embed = [":onboard_lib"],
    visibility = ["//visibility:public"],
)
