load("@rules_java//java:defs.bzl", "java_binary", "java_library", "java_test")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "srcs",
    srcs = glob(["**"]) + [
        "//projects/Leetcode/src/main/java/uk/co/amrik/leetcode:srcs",
        "//projects/Leetcode/src/test/java/uk/co/amrik/leetcode:srcs"
    ]
)
