---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: 6.6.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    deploymentMode: SimpleScalable
    loki:
      commonConfig:
        replication_factor: 3
      schemaConfig:
        configs:
        - from: "2024-01-01"
          store: tsdb
          index:
            prefix: loki_index_
            period: 24h
          object_store: s3
          schema: v13
      storage:
        type: 's3'
        bucketNames:
          chunks: loki-chunks
          ruler: loki-ruler
          admin: loki-admin
        s3:
          endpoint: https://minio.amrik-hl.svc.cluster.local.:9000/loki
          s3ForcePathStyle: false
          secretAccessKey: "${SECRET_LOKI_SECRET_ACCESS_KEY}"
          accessKeyId: "${SECRET_LOKI_ACCESS_KEY}"
          insecure: false
    singleBinary:
      replicas: 3
