---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 30m
  url: https://grafana.github.io/helm-charts
  timeout: 3m
