---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflared
  namespace: flux-system
spec:
  targetNamespace: network
  commonMetadata:
    labels:
      app.kubernetes.io/name: cloudflared
  path: ./infra/kubernetes/cluster-01/apps/networking/cloudflared/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: code
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m


