oci = use_extension("@rules_oci//oci:extensions.bzl", "oci")

# renovate: datasource=docker depName=docker.io/linuxserver/wireguard
oci.pull(
    name = "wireguard",
    digest = "sha256:dca67384e3e9a5bcc288461fa983e6fcb0e248e5a2d8e5b3e5d3f753bfac3e35",
    image = "docker.io/linuxserver/wireguard",
    platforms = [
        "linux/amd64",
        "linux/arm64",
    ],
)
use_repo(
    oci,
    "wireguard",
    "wireguard_linux_amd64",
    "wireguard_linux_arm64",
)
