oci = use_extension("@rules_oci//oci:extensions.bzl", "oci")

# renovate: datasource=docker depName=docker.io/linuxserver/wireguard
oci.pull(
    name = "wireguard",
    digest = "sha256:bf03578ef7318ccc7675b4a82beac4d35cd0da2253194f6b6ecf61656b40f0ee",
    image = "docker.io/linuxserver/wireguard",
    platforms = [
        "linux/amd64",
        "linux/arm64",
    ],
)
use_repo(
    oci,
    "wireguard",
    "wireguard_linux_amd64",
    "wireguard_linux_arm64",
)
