unifi:
    username: ENC[AES256_GCM,data:hSrbENo=,iv:36xVoQTMNdED5dmv5jF4veD2aBSh2jK1JXNdYjlbuTM=,tag:RxnmjMi5iDlgYyxvN47Q+w==,type:str]
    password: ENC[AES256_GCM,data:BfuMfnrQF6oB0P5s,iv:wZQz8fjcj7F6cA9AHfffuneMRgToIuLLsEstQO+I7WA=,tag:Jxuv0qWNVF4y7O48vPGXTw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age165angy86ctnzjrmf8rsm8r7u8lcvactktcgmq0q8vadldv690f7skvxwk6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNENETWRlajdKZTVPT3Y5
            c20yZjdyeXpuTm11ckhQTWZzQk5tRGcySTAwCllxRnVaNHgxK05aUkQxNTZzNVJV
            ZHpmcjhnMXJpWDVmT3BiWEFXa1NxZjAKLS0tICtqVVlmRXk4VkVQT1F3ZDNKaHln
            elhIS2xqVU1EM0huRHVTS0p2NEcwVEUKXP94xGmRMj2ljJ88UHdTtf7oY9C/WXJN
            cc1Y/NO3v1nNZLXg86BIVMO4v901c/bq91aRbt4KGN786zz92e8NoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-27T16:20:53Z"
    mac: ENC[AES256_GCM,data:NFicbaIiFRL/I1iskKOW6CsZCqiFbKmIRhOXnqLud9kDm2w6n4fM1yAaGn98GxUManIAs5d1pSLaQcFqFs4YlyLsYJECxpiag+wUnuBxDm7YOYmavs5lqgV6Kpv9hiwPYqI1MMkv549QhZiZ/qh2OnKmKf2C1EUfZ4xG+RZWqeM=,iv:cHQ6D5yxO+A2M/aHzLUYVVzbWeZL1/6sKqqi4Cd1x/k=,tag:p7OkftKMbl5XE2VbXIzeXw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
