apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 1m
  chart:
    spec:
      chart: tailscale-operator
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: tailscale
      interval: 1m
  values:
    apiServerProxyConfig:
      mode: "true"
  valuesFrom:
    - kind: Secret
      name: tailscale-oauth-credentials
      valuesKey: clientId
      targetPath: oauth.clientId
    - kind: Secret
      name: tailscale-oauth-credentials
      valuesKey: clientSecret
      targetPath: oauth.clientSecret
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  timeout: 5m
