oci = use_extension("@rules_oci//oci:extensions.bzl", "oci")

# renovate: datasource=docker depName=docker.io/linuxserver/qbittorrent
oci.pull(
    name = "qbittorrent",
    digest = "sha256:dd24a5f3db32bc1425d3f8dc95e8aca8ac5a35905d798171230edf33f516d9a4",
    image = "docker.io/linuxserver/qbittorrent",
    platforms = [
        "linux/amd64",
        "linux/arm64",
    ],
)
use_repo(
    oci,
    "qbittorrent",
    "qbittorrent_linux_amd64",
    "qbittorrent_linux_arm64",
)
