oci = use_extension("@rules_oci//oci:extensions.bzl", "oci")

# renovate: datasource=docker depName=docker.io/linuxserver/qbittorrent
oci.pull(
    name = "qbittorrent",
    digest = "sha256:2be038f3421f60f62e8e4bf201f66f385b68e4fbc9ed3ab79051069ea22e2650",
    image = "docker.io/linuxserver/qbittorrent",
    platforms = [
        "linux/amd64",
        "linux/arm64",
    ],
)
use_repo(
    oci,
    "qbittorrent",
    "qbittorrent_linux_amd64",
    "qbittorrent_linux_arm64",
)
