apiVersion: v1
kind: ConfigMap
metadata:
  name: homeassistant
  namespace: default
data:
  configuration.yaml: |
    http:
      server_port: 8123
      base_url: ha.amrik.xyz
      use_x_forwarded_for: true
      trusted_proxies: 127.0.0.1
