oci = use_extension("@rules_oci//oci:extensions.bzl", "oci")

# renovate: datasource=docker depName=docker.io/homeassistant/home-assistant
oci.pull(
    name = "home-assistant",
    digest = "sha256:612d76760b544cb40b7ba01387fdac964c59a6a550a50a4d30b4773c822d2918",
    image = "docker.io/homeassistant/home-assistant",
    platforms = [
        "linux/arm64",
        "linux/amd64",
    ],
)
use_repo(
    oci,
    "home-assistant",
    "home-assistant_linux_amd64",
    "home-assistant_linux_arm64",
)
