oci = use_extension("@rules_oci//oci:extensions.bzl", "oci")

# renovate: datasource=docker depName=docker.io/homeassistant/home-assistant
oci.pull(
    name = "home-assistant",
    digest = "sha256:a1bc133af84ee6505fe2c266d9805b7c75b780dfdc188edfee3b11e8f3cd8efe",
    image = "docker.io/homeassistant/home-assistant",
    platforms = [
        "linux/arm64",
        "linux/amd64",
    ],
)
use_repo(
    oci,
    "home-assistant",
    "home-assistant_linux_amd64",
    "home-assistant_linux_arm64",
)
