oci = use_extension("@rules_oci//oci:extensions.bzl", "oci")

# renovate: datasource=docker depName=docker.io/linuxserver/sonarr
oci.pull(
    name = "sonarr",
    digest = "sha256:633e0e66d85ce4e9172608a37d3d24e124b3e485fc0d946f533c3bb5875227e9",
    image = "docker.io/linuxserver/sonarr",
    platforms = [
        "linux/amd64",
        "linux/arm64",
    ],
)
use_repo(
    oci,
    "sonarr",
    "sonarr_linux_amd64",
    "sonarr_linux_arm64",
)
