oci = use_extension("@rules_oci//oci:extensions.bzl", "oci")

# renovate: datasource=docker depName=docker.io/linuxserver/sonarr
oci.pull(
    name = "sonarr",
    digest = "sha256:f247545d23ba8b233d6604575347e48a623fe6ad75dda02348bf81917f3b5c06",
    image = "docker.io/linuxserver/sonarr",
    platforms = [
        "linux/amd64",
        "linux/arm64",
    ],
)
use_repo(
    oci,
    "sonarr",
    "sonarr_linux_amd64",
    "sonarr_linux_arm64",
)
