name: Only PRs allowed by specific authors
on:
  pull_request:
    branches:
      - main

jobs:
  test-image:
    permissions: 
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: PR Comment warning
        if: github.event.pull_request.user.login == 'AmrikSD'
        uses: thollander/actions-comment-pull-request@v3
        with:
          message-id: ${{ github.event.pull_request.number }}
          message: |
            ### ⚠️This PR will be overwritten by changes in the `my/repo` repository
            You probably want to make changes in the `my/repo`.
            No changes to this, or any cluster repository will persist, all code is managed through the `templates/platform-managed-clusters` repositories.
            
            If you're still confused, please reach out in #slack
