name: CD
on:
  push:
    branches:
      - main

jobs:
  deploy-via-tailscale:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.7"

      - name: Setup SOPS
        uses: nhedger/setup-sops@v2
        with:
          version: "3.9.1"

      - name: Run SOPS
        run: sops -v
      - name: Run Terraform
        run: terraform -v
      - name: Run Terraform plan
        run: |
          terraform -chdir=infra plan
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}


      - name: Connect Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
          tags: tag:ci
      - name: quick check
        run: |
            curl 10.3.164.158:17878
