name: Check that image builds
on:
  pull_request:

jobs:
  test-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check that the image builds
        run: bazel test //...
