name: Check that image builds
on:
  pull_request:

jobs:
  test-image:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Bazel
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'WORKSPACE', 'WORKSPACE.bazel', 'MODULE.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-
      - name: Check that the image builds
        uses: actions/checkout@v4
        run: bazel test //...
