name: Push docker images

permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  get-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - name: Cache Bazel
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'WORKSPACE', 'WORKSPACE.bazel', 'MODULE.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-
      - name: Generate Matrix
        id: generate-matrix
        run: |
          MATRIX=$(bazel query 'kind("oci_push", //infra/containers/...)' | jq -R -s -c '{"include": [split("\n")[] | select(. != "")] | map({target: .})}')
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT
  push-images:
    needs: get-matrix
    runs-on: ubuntu-latest
    if: needs.get-matrix.outputs.matrix != '[]' # Only run if images have changed
    strategy:
      matrix: ${{ fromJson(needs.get-matrix.outputs.matrix) }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push
        run: bazel run ${{matrix.target}}

