name: "Terraform Plan"
on:
  pull_request:
    branches: ["main"]
    paths: ["infra/**"]

concurrency:
  group: terraform-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout Pull Request Branch
        uses: actions/checkout@v4
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.15.7"

      - name: Setup SOPS
        uses: nhedger/setup-sops@v2
        with:
          version: "3.11.0"

      - name: Terraform Init & Plan
        id: plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        run: |
          terraform -chdir=infra init
          terraform -chdir=infra validate
          terraform -chdir=infra plan -no-color -out .planfile

      - name: Post PR comment
        uses: borchero/terraform-plan-comment@v2
        with:
          token: ${{ steps.app-token.outputs.token }}
          skip-empty: true
          working-directory: "./infra"
          header: 📝 Terraform Plan
          planfile: .planfile
